### ISSUE TITLE
Multi Thread

### ISSUE THREAD

**Issue by mehranexpert** [Ethical-H4CK3R/Pulse#1]
can add Multi Thread to make it faster ?

**Comment by Ethical-H4CK3R** [comment]
*mechanize* is **not** thread safe, and also if you attempt too fast you get **locked out**

**Comment by mehranexpert** [comment]
after while running i got this error

```
Traceback (most recent call last):
  File "Pulse.py", line 303, in <module>
    BruteForce(username,wordlist,url,_username,_password).ai()
  File "Pulse.py", line 191, in ai
    self.refresh()
  File "Pulse.py", line 94, in refresh
    self.ipAdd=self.ipAddr()
  File "Pulse.py", line 139, in ipAddr
    return self.brwsr.open('http://icanhazip.com/').read()
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 403: Forbidden

```

**Comment by Ethical-H4CK3R** [comment]
which site were you brute forcing at the time?

**Comment by mehranexpert** [comment]
Instagram

**Comment by Ethical-H4CK3R** [comment]
Okay thanks, I'll look at it later.

**Comment by Ethical-H4CK3R** [comment]
Is the issue solved

**Comment by Ethical-H4CK3R** [comment]
Try the newer version called: [hyprPulse](https://github.com/Ethical-H4CK3R/hyprPulse)
