### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peytzz** [Ethical-H4CK3R/Pulse#23]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pulse.py", line 120, in setupPasswords
    with open(self.wordlist,'r') as passwords:
IOError: [Errno 2] No such file or directory: 'password.txt'

what did i do wrong?

**Comment by peytzz** [comment]
sorry I know whats the problem, it is now working. very nice! but just slow. what do you recommend maximum number in the password list?

**Comment by Ethical-H4CK3R** [comment]
for what site

**Comment by peytzz** [comment]
facebook

**Comment by Juniorn1003** [comment]
I made a better version of Facebook/Twitter/Instagram Bruteforce script, come check it out.
https://github.com/Juniorn1003/Faitagram

**Comment by Ethical-H4CK3R** [comment]
Try the newer version called: [hyprPulse](https://github.com/Ethical-H4CK3R/hyprPulse)
